/**
 * generated by Xtext 2.10.0
 */
package it.polito.security.esp.validation;

import it.polito.security.esp.validation.AbstractRulesLanguageValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class RulesLanguageValidator extends AbstractRulesLanguageValidator {
}
