/*
 * generated by Xtext 2.12.0
 */
package it.polito.security.esp.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractRulesLanguageValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(it.polito.security.esp.rulesLanguage.RulesLanguagePackage.eINSTANCE);
		return result;
	}
	
}
