/**
 * generated by Xtext 2.12.0
 */
package it.polito.security.esp.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import it.polito.security.esp.RulesLanguageRuntimeModule;
import it.polito.security.esp.RulesLanguageStandaloneSetup;
import it.polito.security.esp.ide.RulesLanguageIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class RulesLanguageIdeSetup extends RulesLanguageStandaloneSetup {
  @Override
  public Injector createInjector() {
    RulesLanguageRuntimeModule _rulesLanguageRuntimeModule = new RulesLanguageRuntimeModule();
    RulesLanguageIdeModule _rulesLanguageIdeModule = new RulesLanguageIdeModule();
    return Guice.createInjector(Modules2.mixin(_rulesLanguageRuntimeModule, _rulesLanguageIdeModule));
  }
}
