/**
 * generated by Xtext 2.12.0
 */
package it.polito.security.esp.ide;

import it.polito.security.esp.ide.AbstractRulesLanguageIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class RulesLanguageIdeModule extends AbstractRulesLanguageIdeModule {
}
