/*
 * generated by Xtext 2.10.0
 */
package it.polito.security.esp


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RulesLanguageStandaloneSetup extends RulesLanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new RulesLanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
