/*
 * generated by Xtext 2.10.0
 */
package it.polito.security.esp


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class RulesLanguageRuntimeModule extends AbstractRulesLanguageRuntimeModule {
}
