/*
 * generated by Xtext 2.12.0
 */
package it.polito.security.esp.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRulesLanguageScopeProvider extends DelegatingScopeProvider {
}
