/**
 * generated by Xtext 2.10.0
 */
package it.polito.security.esp;

import it.polito.security.esp.AbstractRulesLanguageRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class RulesLanguageRuntimeModule extends AbstractRulesLanguageRuntimeModule {
}
