/**
 * generated by Xtext 2.10.0
 */
package it.polito.security.esp;

import it.polito.security.esp.RulesLanguageStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class RulesLanguageStandaloneSetup extends RulesLanguageStandaloneSetupGenerated {
  public static void doSetup() {
    new RulesLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
