/*
 * generated by Xtext 2.12.0
 */
package it.polito.security.esp.parser.antlr;

import com.google.inject.Inject;
import it.polito.security.esp.parser.antlr.internal.InternalRulesLanguageParser;
import it.polito.security.esp.services.RulesLanguageGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class RulesLanguageParser extends AbstractAntlrParser {

	@Inject
	private RulesLanguageGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRulesLanguageParser createParser(XtextTokenStream stream) {
		return new InternalRulesLanguageParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public RulesLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RulesLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
