/*
 * generated by Xtext 2.12.0
 */
package it.polito.security.esp.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RulesLanguageAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("it/polito/security/esp/parser/antlr/internal/InternalRulesLanguage.tokens");
	}
}
