/*
 * generated by Xtext 2.12.0
 */
package it.polito.security.esp.ui;

import com.google.inject.Injector;
import it.polito.security.esp.rules.ui.internal.RulesActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RulesLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return RulesActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return RulesActivator.getInstance().getInjector(RulesActivator.IT_POLITO_SECURITY_ESP_RULESLANGUAGE);
	}
	
}
