/**
 * generated by Xtext 2.10.0
 */
package it.polito.security.esp.ui.contentassist;

import it.polito.security.esp.ui.contentassist.AbstractRulesLanguageProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class RulesLanguageProposalProvider extends AbstractRulesLanguageProposalProvider {
}
