/**
 * generated by Xtext 2.12.0
 */
package it.polito.security.esp.rulesLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see it.polito.security.esp.rulesLanguage.RulesLanguagePackage#getCondition()
 * @model
 * @generated
 */
public interface Condition extends EObject
{
} // Condition
