/**
 * generated by Xtext 2.12.0
 */
package it.polito.security.esp.rulesLanguage;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.polito.security.esp.rulesLanguage.Rule#getName <em>Name</em>}</li>
 *   <li>{@link it.polito.security.esp.rulesLanguage.Rule#getConditions <em>Conditions</em>}</li>
 *   <li>{@link it.polito.security.esp.rulesLanguage.Rule#getAction <em>Action</em>}</li>
 * </ul>
 *
 * @see it.polito.security.esp.rulesLanguage.RulesLanguagePackage#getRule()
 * @model
 * @generated
 */
public interface Rule extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see it.polito.security.esp.rulesLanguage.RulesLanguagePackage#getRule_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link it.polito.security.esp.rulesLanguage.Rule#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Conditions</b></em>' containment reference list.
   * The list contents are of type {@link it.polito.security.esp.rulesLanguage.Condition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Conditions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditions</em>' containment reference list.
   * @see it.polito.security.esp.rulesLanguage.RulesLanguagePackage#getRule_Conditions()
   * @model containment="true"
   * @generated
   */
  EList<Condition> getConditions();

  /**
   * Returns the value of the '<em><b>Action</b></em>' attribute.
   * The literals are from the enumeration {@link it.polito.security.esp.rulesLanguage.Action}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Action</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action</em>' attribute.
   * @see it.polito.security.esp.rulesLanguage.Action
   * @see #setAction(Action)
   * @see it.polito.security.esp.rulesLanguage.RulesLanguagePackage#getRule_Action()
   * @model
   * @generated
   */
  Action getAction();

  /**
   * Sets the value of the '{@link it.polito.security.esp.rulesLanguage.Rule#getAction <em>Action</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action</em>' attribute.
   * @see it.polito.security.esp.rulesLanguage.Action
   * @see #getAction()
   * @generated
   */
  void setAction(Action value);

} // Rule
